import './globals.css'
import { Metadata } from 'next'
import Header from './header'

export const metadata: Metadata = {
  title: 'Do Not Give Up',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
